### ISSUE TITLE
TypeError: 'mark' called on an object that does not implement interface Performance

### ISSUE THREAD

**Issue by sanchit-kialo** [sinonjs/lolex#200]
* Lolex version: 2.7.1
* Environment: Firefox 62.0b17 - macOS 10.13.6
* Other libraries you are using: ReactDOM (development)

**What did you expect to happen?**
No Error to be thrown

**What actually happens**
A TypeError was thrown
`TypeError: 'mark' called on an object that does not implement interface Performance`

**How to reproduce**
`lolex.install();`
This happens when using the default `lolex.install();`

When subsequently calling `performance.mark()`, the TypeError is thrown (in my case, `performance.mark` is called by ReactDOM.development)

A workaround for this issue that I have found is to use this instead:
`lolex.install({
            toFake: [
                'setTimeout',
                'clearTimeout',
                'setImmediate',
                'clearImmediate',
                'setInterval',
                'clearInterval',
                'Date',
                'nextTick',
                'hrtime',
            ],
        });`

Based on my preliminary research, it looks like this issue may have been introduced by #160 in response to issue #136 
I am unsure if this method of recreating the performance object on the clock is carrying over the underlying interface type.

**Comment by fatso83** [comment]
Veriifed by adding this test and running `npm run test-headless`

```javascript
            it("should not throw an error on calling performance.mark", function() {
                this.clock = lolex.install();
                assert.isFunction(global.performance.mark);
                refute.exception(function() {
                    global.performance.mark("a name");
                });
            });
```
