### PR TITLE
Restore Date object support broken by PR #556

### PR DESCRIPTION
**Pull request by adspacheco**
#### Purpose (TL;DR) - mandatory                                                                                                          
                                                                                                                                            
Fix cross-realm Date regression introduced in [#556](https://github.com/sinonjs/fake-timers/pull/556).                                                                                       
                                                                                                                                            
#### Background (Problem in detail)                                                                                                       
                                                                                                                                            
The public API accepts `Date | number`, but the change in #556 from `typeof epoch.getTime === "function"` to `instanceof Date` broke support for Date objects from different realms (iframes, vm contexts, etc.), since `instanceof` fails across realms.                      
                                                                                                                                            
Error: `TypeError: now should be milliseconds since UNIX epoch`                                                                           
                                                                                                                                            
Reproduction:                                                                                                                             
                                                                                                                                            
```js                                                                                                                                     
const vm = require("vm");                                                                                                                 
const FakeTimers = require("@sinonjs/fake-timers");                                                                                       
const crossRealmDate = vm.runInNewContext("new Date('2026-04-02')");                                                                      
const clock = FakeTimers.install();                                                                                                       
clock.setSystemTime(crossRealmDate); // throws TypeError                                                                                  
```      
                                                                                                                                     
#### Solution                                                                                                                                  
                                                                                                                                            
Restore the original duck-typing approach `(typeof epoch.getTime === "function")` that worked before #556.

### CODE REVIEW

**Comment by fatso83** [comment]
added the missing regression test in aa15fde41f5bda6e118adcffdcbd012d52ec4bcc for you, as I introduced the regression 😉

**Comment by fatso83** [comment]
Unfortunately, this fix was incomplete, as the typing now breaks. This is what I get for not ensuring the types are built as part of the github actions. At least I know that now 😄 
```
src/fake-timers-src.js:642:26 - error TS2339: Property 'getTime' does not exist on type 'number | Date'.
  Property 'getTime' does not exist on type 'number'.

642         if (typeof epoch.getTime === "function") {
                             ~~~~~~~

src/fake-timers-src.js:643:26 - error TS2339: Property 'getTime' does not exist on type 'number | Date'.
  Property 'getTime' does not exist on type 'number'.

643             return epoch.getTime();
                             ~~~~~~~


Found 2 errors in the same file, starting at: src/fake-timers-src.js:642

```

I'll get it fixed.

**Comment by fatso83** [comment]
types are now always built and the type regression fixed in d43b719

release 15.3.1 out in a few jiffies
