### ISSUE TITLE
TypeScript doesn't compile

### ISSUE THREAD

**Issue by alecgibson** [sinonjs/lolex#558]
It looks like type definitions were [completely reworked in v15.3.0](https://github.com/sinonjs/fake-timers/commit/8f096a8b0392dbfe16c76ccedaed3c1a56d8ce54#diff-b417af1ed78243852472c4eb3b4456a4e5336cc15d4d6fac0ea00bb4dcc3355aR108).

For a [barebones install repro](https://stackblitz.com/edit/vitejs-vite-c63jwkxe?file=tsconfig.json), this has broken TypeScript compilation (see below).

There are 2 issues:

 1. `FakeTimerInstallOpts` was renamed to `Config`, breaking the [`@types/sinon` import](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/8fe0c8af85c80359cf96a19fb00e423332cf700f/types/sinon/index.d.ts#L1185). I've already raised a PR against DefinitelyTyped to fix this downstream: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/74827
 2. It looks like `withGlobal` has a duplicate declaration from the automated type generation. I can't pretend to know enough about how types are generated in this library to raise a fix. See  below for the compilation errors. This is the problematic part of the type definition: https://github.com/sinonjs/fake-timers/blob/00db41eff2a53bb7c19bade689bb5c9425b4df23/types/fake-timers-src.d.ts#L556-L560

```
❯ npm run build

> vite-typescript-starter@0.0.0 build
> tsc

node_modules/@sinonjs/fake-timers/types/fake-timers-src.d.ts:558:18 - error TS2300: Duplicate identifier 'withGlobal'.

558 declare function withGlobal(_global: any): FakeTimers;
                     ~~~~~~~~~~

node_modules/@sinonjs/fake-timers/types/fake-timers-src.d.ts:558:18 - error TS2395: Individual declarations in merged declaration 'withGlobal' must be all exported or all local.

558 declare function withGlobal(_global: any): FakeTimers;
                     ~~~~~~~~~~

node_modules/@sinonjs/fake-timers/types/fake-timers-src.d.ts:562:20 - error TS2300: Duplicate identifier 'withGlobal'.

562 export declare var withGlobal: typeof withGlobal;
                       ~~~~~~~~~~

node_modules/@sinonjs/fake-timers/types/fake-timers-src.d.ts:562:20 - error TS2395: Individual declarations in merged declaration 'withGlobal' must be all exported or all local.

562 export declare var withGlobal: typeof withGlobal;
                       ~~~~~~~~~~

node_modules/@sinonjs/fake-timers/types/fake-timers-src.d.ts:562:20 - error TS2502: 'withGlobal' is referenced directly or indirectly in its own type annotation.

562 export declare var withGlobal: typeof withGlobal;
                       ~~~~~~~~~~

node_modules/@types/sinon/index.d.ts:1185:53 - error TS2694: Namespace '"/home/projects/vitejs-vite-c63jwkxe/node_modules/@sinonjs/fake-timers/types/fake-timers-src"' has no exported member 'FakeTimerInstallOpts'.

1185         useFakeTimers: boolean | Partial<FakeTimers.FakeTimerInstallOpts>;
                                                         ~~~~~~~~~~~~~~~~~~~~

node_modules/@types/sinon/index.d.ts:1335:67 - error TS2694: Namespace '"/home/projects/vitejs-vite-c63jwkxe/node_modules/@sinonjs/fake-timers/types/fake-timers-src"' has no exported member 'FakeTimerInstallOpts'.

1335         useFakeTimers(config?: number | Date | Partial<FakeTimers.FakeTimerInstallOpts>): SinonFakeTimers;
                                                                       ~~~~~~~~~~~~~~~~~~~~


Found 7 errors in 2 files.

Errors  Files
     5  node_modules/@sinonjs/fake-timers/types/fake-timers-src.d.ts:558
     2  node_modules/@types/sinon/index.d.ts:1185
```

**Comment by AviVahl** [comment]
saw both issues on our end.
FYI @fatso83

**Comment by AviVahl** [comment]
@fatso83 I've opened a PR to address this. I've validated the fix downstream.
